### ISSUE TITLE
Fix

### ISSUE THREAD

**Issue by tejovanthn** [meerasndr/facebook-clone#1]
https://github.com/meerasndr/facebook-clone/blob/74af5e984a33572988f41fb3dc3b0dd944dcb086/src/App.js#L45

`postComments` adds a comment to a given post. 
We do this by appending the `comments` to the existing state's `postcomment` array.
A `patch` request is then fired to update the `postcomment` for the given post, and the app`state` is updated with the response in-situ to maintain the existing order of posts.

```
  postComments = (id, comments) => {
    const existingComments =
      this.state.list.find(post => post.id === id).postcomments || []
    axios
      .patch(`http://localhost:8080/posts/${id}`, {
        postcomments: [comments, ...existingComments],
      })
      .then(result => {
        // https://stackoverflow.com/a/35206193
        const foundIndex = this.state.list.findIndex(post => post.id === id)
        const list = [...this.state.list]
        list[foundIndex] = result.data
        this.setState({ list })
      })
  }
```

**Comment by meerasndr** [comment]
This worked very well. I have merged this code to the master branch. Thank you!
